version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=poem_wizard_api
    volumes:
      - ./postgres:/var/lib/postgresql/data