version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=poem_wizard_api
    volumes:
      - pgdb:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@wizard.com
      - PGADMIN_DEFAULT_PASSWORD=pgadminpass
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdb:
  pgadmin:
