version: '3.9'
services:
  server:
    build:
      context: .
      target: final
    ports:
      - 3000:3000
    environment:
      - PG_HOST=db
      - PG_DBNAME=wizard
      - PG_USER=postgres
      - PG_PASSWORD=postgrespass
    volumes:
      - server-files:/files
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=wizard
      - POSTGRES_PASSWORD=postgrespass
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
  server-files:
